### ISSUE TITLE
Render the whole year, even if only several values are provided

### ISSUE THREAD

**Issue by stefansurkamp** [grubersjoe/react-activity-calendar#33]
Hey. I love the project and would like to suggest an improvement/feature :) 

I was wondering if it makes sense to automatically fill the whole year (or a designated range) with 0-values if none are provided for a certain date?

Example of an actual use case:
Currently it's necessary to have an array with 365 entries (ranging from 2023-01-01 to 2023-12-31, mostly "empty") to render a  full-year graph. As a user of this component it's cumbersome to fill an array with all those value, if all data I actually have is e.g. 

```js
const data = [
  {
    date: "2023-01-12",
    count: 2,
    level: 1,
  },
  {
    date: "2023-01-13",
    count: 0,
    level: 0,
  },
]
```

What do you think? :)

**Comment by grubersjoe** [comment]
Hey. Glad you like it :)!

It's probably not obvious and should be documented, but the component will fill "holes" in the calendar automatically, because it internally expects a continuous sequence of days. [See here](https://github.com/grubersjoe/react-activity-calendar/blob/main/src/utils/index.ts#L54). So you could simply do something like this:

```ts
const data = [
  {
    date: '2023-01-01', // start
    count: 0,
    level: 0,
  },
  {
    date: '2023-01-12',
    count: 2,
    level: 1,
  },
  {
    date: '2023-12-31', // end, all days in between will be filled with empty data
    count: 0,
    level: 0,
  },
]
```

**Comment by stefansurkamp** [comment]
Aaah, that is very handy and will definitely work for me :)
Thanks for your quick help!
