### ISSUE TITLE
NEXT.Js14 Module Not Found Error

### ISSUE THREAD

**Issue by parthmahajan008** [grubersjoe/react-activity-calendar#53]
![WhatsApp Image 2024-01-13 at 7 18 55 PM](https://github.com/grubersjoe/react-activity-calendar/assets/97579934/6d53ca4f-21e0-4edf-b19c-eda45120089d)
I am on latest version of Nextjs14, using pnpm as node manager

**Comment by grubersjoe** [comment]
Hey. Thanks for reporting, this is fixed in `react-activity-calendar@2.2.5` now. Can you please try this version? 

There have been two issues:

- I accidentally broke the npm package by switching from the `main` field to the `browser` one in `package.json`: https://github.com/grubersjoe/react-activity-calendar/commit/963985b3d7ef48b892b09d2eabbef2b5dbf92751
- React Server Components were not supported yet, because the `'use client'` directive was missing
