### ISSUE TITLE
Use with external Tooltip with custom text

### ISSUE THREAD

**Issue by hugobarragon** [grubersjoe/react-activity-calendar#6]
Hi,
is it possible to integrate with tooltip for example Material ui and add custom text to tooltip?

**Comment by mesutcifci** [comment]
Hi. Can we change tooltip text?

**Comment by iamkroot** [comment]
+1 for this feature request.
While #19 was indeed a step in the right direction, the `{{count}}` replacement is too restrictive. In my case, the `count` is a time duration such as `3000s`, and I would like to humanize it to "50 minutes", instead of simply printing it as "3000 seconds". 

It would be more powerful to also accept a callback at the `labels.tooltip` property, like this-
```js
labels.tooltip = (date, count) => ...; // any abitrary func that returns a string
```

**Comment by grubersjoe** [comment]
Hey. I'm currently on vacation but I can look I to this after I come back end of February.

**Comment by fweffort** [comment]
#26 will render custom props, so you could:
item = {
count: 123,
foo: "asdfasdfasdf",
bar: "fsdfsdf",
date: "date"}

tooltip = `Custom tooltip with text {{foo}} and. {{bar}} `

**Comment by grubersjoe** [comment]
I think I found a good way to support all kinds of different tooltip components through a render property now. However, this is going to be a breaking change and will consequently be released with v2.

**Comment by grubersjoe** [comment]
Hey. I've just released v2 which enables you to use all kinds of tooltip components. Check out these [examples](https://grubersjoe.github.io/react-activity-calendar/?path=/story/react-activity-calendar--with-tooltips) for `@mui/material`  and `react-tooltip` v5. Please let me know if this solves your requirements.
