### ISSUE TITLE
Allow support for arbitrary number of columns/rows not just date based

### ISSUE THREAD

**Issue by domingaspleckauskas** [grubersjoe/react-activity-calendar#64]
I know it says `calendar` in the name but it would be good to have the ability to set custom columns/rows to allow more versatility.

My example use case:
- each box would represent some page
- the colour would represent how recently it was updated

**Comment by grubersjoe** [comment]
Hey. I see your use case but the whole code base revolves about implementing a calendar. Adding this kind of functionality would need to change the whole component concept. So I don't think this proposal fits into `react-activity-calendar`. 

For example, how would the input data structure look like? I suppose it would need to specify x/y coordinates instead of a date:

```json
[
  {
    "x": 0,
    "y": 2,
    "count": 2,
    "level": 1
  },
  {
    "x": 7,
    "y": 4,
    "count": 16,
    "level": 3
  }
]
```

So I think having such a component in general is not a bad idea, but it should probably be another, independent component that could reuse some of the rendering logic.
